import { spawn, type Subprocess } from "bun";
import { randomUUID } from "node:crypto";
import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  unlinkSync,
  writeFileSync,
} from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import type { SessionKind } from "../shared/types.ts";
import { config } from "./config.ts";
import { allLiveSessionIds, allSessionIds, sessionMeta, setSessionPort } from "./db.ts";
import { extractGotty, extractSessionInit, extractSessionInitZsh } from "./embedded.ts";
import { setStatus } from "./status.ts";

// One GoTTY process per session. GoTTY itself forks a fresh shell for EACH
// WebSocket connection, so two browsers on the same session get independent
// shells (the "per-client shell" model) while we still track one port/session.

// On-disk fallbacks for dev. In the compiled binary, gotty + session-init are
// extracted from the embedded bunfs at first use via embedded.ts.
const REPO_ROOT = join(import.meta.dir, "../..");
const DISK_GOTTY = config.gottyBin ?? join(REPO_ROOT, "bin/gotty");
const DISK_INIT = join(REPO_ROOT, "src/server/session-init.bash");
const DISK_INIT_ZSH = join(REPO_ROOT, "src/server/session-init.zsh");
const BASE_PORT = config.gottyBasePort;

async function gottyBin(): Promise<string> {
  // User-configured gottyBin always wins (even in compiled mode).
  if (config.gottyBin) return config.gottyBin;
  return (await extractGotty()) ?? DISK_GOTTY;
}

async function sessionInitPath(): Promise<string> {
  return (await extractSessionInit()) ?? DISK_INIT;
}

async function sessionInitZshPath(): Promise<string> {
  return (await extractSessionInitZsh()) ?? DISK_INIT_ZSH;
}

// The user's login shell, e.g. "/usr/bin/zsh". Falls back to bash when unset.
function userShellPath(): string {
  return process.env.SHELL || "bash";
}

// A custom ZDOTDIR makes zsh skip the user's ~/.zshenv at its normal startup
// phase (before /etc/zprofile + /etc/zshrc). This shim, written as the zdotdir's
// .zshenv, restores that ordering: source the user's real .zshenv, then re-point
// ZDOTDIR back here so zsh still selects our .zshrc next (a user .zshenv that
// sets ZDOTDIR mustn't divert zsh away from our status/startup injection).
const ZSHENV_SHIM = [
  "# AUTO-GENERATED by tabterm. Restores normal ~/.zshenv ordering under our",
  "# custom ZDOTDIR. Point ZDOTDIR at the user's real dir while their .zshenv runs",
  "# (frameworks like prezto/zimfw reference $ZDOTDIR), then re-point it back here",
  "# so zsh still selects our .zshrc next.",
  '_tabterm_self="$ZDOTDIR"',
  'if [[ -n "$_TABTERM_HOME_ZDOTDIR" ]]; then',
  '  export ZDOTDIR="$_TABTERM_HOME_ZDOTDIR"',
  "else",
  "  unset ZDOTDIR",
  "fi",
  '[[ -f "${ZDOTDIR:-$HOME}/.zshenv" ]] && source "${ZDOTDIR:-$HOME}/.zshenv"',
  'ZDOTDIR="$_tabterm_self"',
  "unset _tabterm_self",
  "",
].join("\n");

// Materialize the zsh init as <cache>/zdotdir/{.zshrc,.zshenv} once, so we can
// launch the user's zsh with ZDOTDIR pointed here — layering our status markers
// + startup command over their own config without touching ~/.zshrc. Returns
// null when the zsh init source can't be found (then we fall back to bash).
let zdotdirPromise: Promise<string | null> | null = null;
function zshZdotdir(): Promise<string | null> {
  if (!zdotdirPromise) {
    zdotdirPromise = (async () => {
      try {
        const src = await sessionInitZshPath();
        if (!existsSync(src)) return null;
        const dir = join(homedir(), ".cache/tabterm/zdotdir");
        mkdirSync(dir, { recursive: true });
        writeIfChanged(join(dir, ".zshrc"), readFileSync(src, "utf8"));
        writeIfChanged(join(dir, ".zshenv"), ZSHENV_SHIM);
        return dir;
      } catch {
        return null;
      }
    })();
  }
  return zdotdirPromise;
}

// Write only when the on-disk content differs, so re-materializing each boot
// doesn't churn mtimes (and zsh's compdump invalidation) for unchanged files.
function writeIfChanged(path: string, content: string): void {
  let cur = "";
  try { cur = readFileSync(path, "utf8"); } catch {}
  if (cur !== content) writeFileSync(path, content);
}

// The shell GoTTY forks for each session, plus any env it needs. By default we
// honor the user's $SHELL: zsh launches via a ZDOTDIR that layers our status +
// startup hooks over their config; bash (or an unknown/missing shell) uses our
// --rcfile init. sessionInit overrides: "off" → bare $SHELL with no injection;
// a path → bash with that custom rcfile (back-compat).
async function shellCommand(): Promise<{ cmd: string[]; env: Record<string, string> }> {
  if (config.sessionInit === "off") return { cmd: [userShellPath()], env: {} };
  if (config.sessionInit) return { cmd: ["bash", "--rcfile", config.sessionInit, "-i"], env: {} };

  const shell = userShellPath();
  if (existsSync(shell) && /(^|\/)zsh$/.test(shell)) {
    const dir = await zshZdotdir();
    if (dir) {
      return {
        cmd: [shell, "-i"],
        env: { ZDOTDIR: dir, _TABTERM_HOME_ZDOTDIR: process.env.ZDOTDIR ?? "" },
      };
    }
  }
  return { cmd: ["bash", "--rcfile", await sessionInitPath(), "-i"], env: {} };
}

// ---- tmux durable-session layer ----------------------------------------------
// Each tabterm session runs inside a tmux session `tt-<id>` on a private server
// socket, so the shell + its programs + scrollback survive a Bun restart/crash
// (gotty just re-attaches). Falls back to a direct child shell when tmux is
// absent or disabled (config.tmux === "off") — behavior then matches pre-tmux.
export const TMUX_SOCKET = "tabterm";
export const tmuxSessionName = (sessionId: string) => `tt-${sessionId}`;

// Resolved tmux binary path, or null when disabled/missing. Cached.
let tmuxBinPromise: Promise<string | null> | null = null;
let tmuxActive = false;
function tmuxBin(): Promise<string | null> {
  if (!tmuxBinPromise) {
    tmuxBinPromise = (async () => {
      const bin = config.tmux === "off" ? null : Bun.which("tmux");
      tmuxActive = bin !== null;
      return bin;
    })();
  }
  return tmuxBinPromise;
}

// Whether sessions are tmux-backed (resolved after the first spawn/poll tick).
// The proxy's OSC-133 status scanner is gated off when this is true: under tmux
// the poller is the single status source for shell sessions (and OSC-133 may not
// survive tmux anyway), so we avoid a dual-writer race. False on no-tmux hosts,
// where the scanner remains the status source.
export function tmuxEnabled(): boolean {
  return tmuxActive;
}

// Load the user's own tmux config first (their theme, status bar, keybindings),
// then apply only the overrides TabTerm needs. Using `-f` means tmux won't
// auto-load these, so we source them explicitly (both common locations, quietly
// = no error if absent). Absolute $HOME paths since `-f` config ~ handling
// varies. Overrides come last so they win:
//   window-size latest — multi-client mirror sizes to the active typer, not the
//     smallest (else two devices clamp each other).
//   mouse on — tmux owns the (alternate) screen while attached, disabling
//     xterm.js scrollback, so the wheel/touch-swipe needs tmux mouse to scroll.
function tmuxConfBody(): string {
  const home = homedir();
  return [
    `source-file -q "${join(home, ".config/tmux/tmux.conf")}"`,
    `source-file -q "${join(home, ".tmux.conf")}"`,
    "set -g window-size latest",
    "set -g mouse on",
    "",
  ].join("\n");
}

let tmuxConfPromise: Promise<string> | null = null;
function tmuxConf(): Promise<string> {
  if (!tmuxConfPromise) {
    tmuxConfPromise = (async () => {
      const dir = join(homedir(), ".cache/tabterm");
      mkdirSync(dir, { recursive: true });
      const path = join(dir, "tmux.conf");
      writeIfChanged(path, tmuxConfBody());
      return path;
    })();
  }
  return tmuxConfPromise;
}

// Push the current tmux.conf into an already-running tmux server. The `-f conf`
// flag only applies when the server first starts, but our tmux server is
// long-lived across Bun restarts — so config changes (e.g. the mouse setting)
// must be re-sourced on boot to take effect without killing the server.
export async function reloadTmuxConf(): Promise<void> {
  const bin = await tmuxBin();
  if (!bin) return;
  try {
    const conf = await tmuxConf();
    spawn([bin, "-L", TMUX_SOCKET, "source-file", conf], { stdout: "ignore", stderr: "ignore" });
  } catch {
    // no server running yet — a fresh server picks up the conf via `-f`
  }
}

// Wrap the base shell command in `tmux new-session -A` so it runs inside a
// durable tmux session. Per-session env is folded into an `env VAR=… <shell>`
// prefix instead of relying on tmux's singleton-server environment (which would
// bleed the first session's vars into later ones). On reattach `-A` ignores the
// command, so the already-running shell/AI command resumes untouched. Returns
// null when tmux is unavailable → caller uses the direct-shell path.
async function tmuxWrap(
  sessionId: string,
  cwd: string | undefined,
  baseCmd: string[],
  sessionEnvVars: Record<string, string>,
): Promise<string[] | null> {
  const bin = await tmuxBin();
  if (!bin) return null;
  const conf = await tmuxConf();
  const envPrefix = Object.entries(sessionEnvVars).map(([k, v]) => `${k}=${v}`);
  return [
    bin, "-L", TMUX_SOCKET, "-f", conf,
    "new-session", "-A", "-s", tmuxSessionName(sessionId),
    ...(cwd ? ["-c", cwd] : []),
    "--", "env", ...envPrefix, ...baseCmd,
  ];
}

// Kill a session's tmux session — used by purge. No-op when tmux is off or the
// session is already gone. Soft-close must NOT call this (it keeps the session
// alive, detached, so reopen resumes the running programs).
export async function killTmuxSession(sessionId: string): Promise<void> {
  const bin = await tmuxBin();
  if (!bin) return;
  try {
    spawn([bin, "-L", TMUX_SOCKET, "kill-session", "-t", tmuxSessionName(sessionId)], {
      stdout: "ignore", stderr: "ignore",
    });
  } catch {
    // server not running / session already gone — nothing to do
  }
}

// Boot reconcile: kill any `tt-<id>` tmux session that has no backing DB row
// (purged while the server was down). Diffs against ALL persisted sessions —
// open AND soft-closed — so a detached soft-closed session's running work is
// never reaped. No-op when tmux is off or the server isn't running.
export async function reapOrphanTmux(): Promise<void> {
  const bin = await tmuxBin();
  if (!bin) return;
  let out = "";
  try {
    const proc = spawn([bin, "-L", TMUX_SOCKET, "list-sessions", "-F", "#{session_name}"], {
      stdout: "pipe", stderr: "ignore",
    });
    out = await new Response(proc.stdout).text();
    await proc.exited;
  } catch {
    return; // no server yet / nothing to reconcile
  }
  const live = new Set(allLiveSessionIds());
  let killed = 0;
  for (const line of out.split("\n")) {
    const name = line.trim();
    if (!name.startsWith("tt-")) continue;
    if (live.has(name.slice(3))) continue;
    try {
      spawn([bin, "-L", TMUX_SOCKET, "kill-session", "-t", name], { stdout: "ignore", stderr: "ignore" });
      killed++;
    } catch {
      // best-effort
    }
  }
  if (killed > 0) console.log(`[gotty] reaped ${killed} orphan tmux session(s)`);
}

// Per-session state dir for AI sessions. We persist one UUID per session up-front;
// session-init.bash then picks --session-id <uuid> (no jsonl in claude's project
// store yet) or --resume <uuid> (jsonl exists) at exec time. Using `--continue`
// would resume whichever conversation in this cwd was touched most recently,
// crossing tabs over after any shell relaunch.
const MARKER_DIR = join(homedir(), ".cache/tabterm/sessions");

function uuidFile(sessionId: string, kind: SessionKind): string {
  return join(MARKER_DIR, `${sessionId}.${kind}.uuid`);
}

function ensureSessionUuid(sessionId: string, kind: SessionKind): string {
  const path = uuidFile(sessionId, kind);
  try {
    const raw = readFileSync(path, "utf8").trim();
    if (/^[0-9a-f-]{36}$/i.test(raw)) return raw;
  } catch {
    // missing or unreadable — fall through and write a fresh one
  }
  mkdirSync(MARKER_DIR, { recursive: true });
  const uuid = randomUUID();
  writeFileSync(path, uuid);
  return uuid;
}

// Env injected on top of process.env for every session. The TABTERM_* vars let
// shell hooks / AI hooks call back into the server (POST /api/sessions/:id/
// status). When `kind` matches a sessionCommands entry we additionally set
// STARTUP_COMMAND + STARTUP_SESSION_ID and let session-init.bash choose
// --session-id vs --resume at exec time. Unknown kinds fall back to a bare
// shell — safer than killing the session.
function sessionEnv(sessionId: string, kind: SessionKind): Record<string, string> {
  const base = {
    TABTERM_SESSION_ID: sessionId,
    TABTERM_BASE_URL: `http://127.0.0.1:${config.port}`,
  };
  if (kind === "shell") return base;
  const entry = config.sessionCommands.find((c) => c.type === kind);
  if (!entry) return base;
  return {
    ...base,
    STARTUP_COMMAND: entry.command,
    STARTUP_SESSION_ID: ensureSessionUuid(sessionId, kind),
  };
}

// Resolve a stored cwd ("", "~", "~/foo", or absolute) to a real directory.
// Returns undefined when the value is empty, doesn't exist, or can't be resolved
// — callers fall back to the server's cwd in that case.
function resolveCwd(stored: string | undefined): string | undefined {
  if (!stored) return undefined;
  const home = homedir();
  let path = stored;
  if (path === "~") path = home;
  else if (path.startsWith("~/")) path = join(home, path.slice(2));
  if (!existsSync(path)) return undefined;
  return path;
}

interface GoTTYProcess {
  proc: Subprocess;
  port: number;
}

const procs = new Map<string, GoTTYProcess>();
let nextPort = BASE_PORT;

// PID files let us SIGKILL orphan gotty children left behind by an ungraceful
// tabterm exit. Without this, an orphan keeps holding its old port — on
// restart, the new gotty fails to bind silently, waitForPort still sees the
// orphan answer, and the session ends up wired to a shell that was launched
// with another session's cwd/env.
function pidFile(sessionId: string): string {
  return join(MARKER_DIR, `${sessionId}.gotty.pid`);
}

function writePidFile(sessionId: string, pid: number): void {
  mkdirSync(MARKER_DIR, { recursive: true });
  writeFileSync(pidFile(sessionId), String(pid));
}

function removePidFile(sessionId: string): void {
  try { unlinkSync(pidFile(sessionId)); } catch {}
}

// Best-effort: kill any gotty children left behind by a previous tabterm crash.
// Called once at startup, before respawnAll. Safe to call when nothing is stale
// (no dir, no files) — it just returns.
export function reapOrphans(): void {
  let files: string[];
  try {
    files = readdirSync(MARKER_DIR);
  } catch {
    return;
  }
  const pidFiles = files.filter((f) => f.endsWith(".gotty.pid"));
  let killed = 0;
  for (const f of pidFiles) {
    const full = join(MARKER_DIR, f);
    try {
      const pid = Number(readFileSync(full, "utf8").trim());
      if (Number.isFinite(pid) && pid > 0) {
        try {
          process.kill(pid, "SIGKILL");
          killed++;
        } catch {
          // ESRCH (already dead) or EPERM — nothing useful to do; the unlink
          // below still clears the stale file.
        }
      }
    } catch {
      // unreadable file — fall through to unlink
    }
    try { unlinkSync(full); } catch {}
  }
  if (killed > 0) console.log(`[gotty] reaped ${killed} orphan gotty process(es)`);
}

// Skip ports the OS already has bound (orphan we couldn't reap, an unrelated
// process, etc.) so spawn() doesn't fight a doomed bind. Cap at 500 attempts
// so a fully-saturated port range fails loudly instead of looping forever.
async function allocatePort(): Promise<number> {
  const used = new Set([...procs.values()].map((p) => p.port));
  for (let i = 0; i < 500; i++) {
    if (used.has(nextPort)) { nextPort++; continue; }
    if (await isAlive(nextPort)) {
      console.warn(`[gotty] port ${nextPort} already in use; skipping`);
      used.add(nextPort);
      nextPort++;
      continue;
    }
    return nextPort++;
  }
  throw new Error(`[gotty] no free port available in range starting at ${BASE_PORT}`);
}

async function waitForPort(port: number, timeoutMs = 3000): Promise<boolean> {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    try {
      const res = await fetch(`http://127.0.0.1:${port}/`);
      if (res.ok || res.status === 401) return true;
    } catch {
      // not listening yet
    }
    await Bun.sleep(50);
  }
  return false;
}

// Spawn a GoTTY process for a session (idempotent). Returns its port.
// Retries on the next port if the spawned gotty dies before binding (e.g.,
// another process slipped onto the port between the probe and the spawn).
export async function ensure(sessionId: string): Promise<number> {
  const existing = procs.get(sessionId);
  if (existing && !existing.proc.killed) return existing.port;

  const [bin, shell] = await Promise.all([gottyBin(), shellCommand()]);
  const meta = sessionMeta(sessionId);
  const cwd = resolveCwd(meta?.cwd);
  if (meta?.cwd && !cwd) {
    console.warn(`[gotty] session ${sessionId} cwd "${meta.cwd}" not found, falling back`);
  }
  const kind = meta?.kind ?? "shell";
  const extraEnv = { ...sessionEnv(sessionId, kind), ...shell.env };

  // tmux-backed when available: gotty runs a `tmux new-session -A` client and
  // the per-session env rides an `env VAR=…` prefix inside the tmux command.
  // Otherwise gotty runs the shell directly with the env on its own process
  // (byte-identical to the pre-tmux behavior).
  const wrapped = await tmuxWrap(sessionId, cwd, shell.cmd, extraEnv);
  const launchCmd = wrapped ?? shell.cmd;
  const launchEnv = wrapped ? {} : extraEnv;

  for (let attempt = 1; attempt <= 5; attempt++) {
    const port = await allocatePort();
    const proc = spawn(
      [
        bin,
        "--port", String(port),
        "--address", "127.0.0.1",
        "--permit-write",
        "--ws-origin", ".*",
        ...launchCmd,
      ],
      {
        stdout: "ignore",
        stderr: "ignore",
        ...(cwd ? { cwd } : {}),
        env: { ...process.env, ...launchEnv } as Record<string, string>,
      },
    );

    // Race readiness against the child exiting — if gotty dies during startup
    // (port collision, bad binary), waitForPort would otherwise be fooled by
    // an orphan answering on the same port.
    const outcome = await Promise.race<"ready" | "exited" | "timeout">([
      waitForPort(port).then((ok) => (ok ? "ready" : "timeout")),
      proc.exited.then(() => "exited" as const),
    ]);

    if (outcome === "ready" && proc.exitCode === null) {
      procs.set(sessionId, { proc, port });
      setSessionPort(sessionId, port);
      if (proc.pid) writePidFile(sessionId, proc.pid);
      console.log(`[gotty] session ${sessionId} -> ${(wrapped ? `tmux ${tmuxSessionName(sessionId)}` : shell.cmd.join(" "))} on :${port}${cwd ? ` (cwd=${cwd})` : ""}`);
      return port;
    }

    try { proc.kill(); } catch {}
    console.warn(
      `[gotty] session ${sessionId} spawn ${outcome} on :${port} (attempt ${attempt}/5); retrying on next port`,
    );
  }

  throw new Error(`[gotty] session ${sessionId} failed to bind a port after 5 attempts`);
}

export function portOf(sessionId: string): number | undefined {
  return procs.get(sessionId)?.port;
}

export function kill(sessionId: string): void {
  const entry = procs.get(sessionId);
  if (!entry) return;
  entry.proc.kill();
  procs.delete(sessionId);
  setSessionPort(sessionId, null);
  removePidFile(sessionId);
  console.log(`[gotty] killed session ${sessionId}`);
}

// Re-spawn GoTTY for every persisted session on server boot (auto-respawn).
export async function respawnAll(): Promise<void> {
  const ids = allSessionIds();
  if (ids.length === 0) return;
  console.log(`[gotty] respawning ${ids.length} session(s) after restart`);
  await Promise.all(ids.map((id) => ensure(id)));
}

export function killAll(): void {
  for (const id of [...procs.keys()]) kill(id);
}

async function isAlive(port: number): Promise<boolean> {
  try {
    const res = await fetch(`http://127.0.0.1:${port}/`, { signal: AbortSignal.timeout(1500) });
    return res.ok || res.status === 401;
  } catch {
    return false;
  }
}

// Periodically ping each GoTTY process; respawn any that has exited or stopped
// responding (P1 health check). Returns a stop function.
export function startHealthMonitor(intervalMs = 30_000): () => void {
  let running = false;
  const timer = setInterval(async () => {
    if (running) return;
    running = true;
    try {
      for (const [sessionId, { proc, port }] of [...procs]) {
        const dead = proc.exitCode !== null || !(await isAlive(port));
        if (dead) {
          console.warn(`[gotty] session ${sessionId} unhealthy on :${port}, respawning`);
          kill(sessionId);
          await ensure(sessionId);
        }
      }
    } finally {
      running = false;
    }
  }, intervalMs);
  return () => clearInterval(timer);
}

// Shell foreground commands that mean "at the prompt" (idle). Anything else
// running in the pane (vim, htop, a build) means "running".
const IDLE_COMMANDS = new Set(
  ["bash", "zsh", "sh", "fish", (userShellPath().split("/").pop() || "bash")],
);

// Drive the sidebar idle/running dot for tmux-backed shell sessions by polling
// each pane's foreground command. OSC-133 markers (the non-tmux status source,
// scanned in proxy.ts) don't survive tmux, so this is the status source under
// tmux. AI sessions are hook-driven (skipped); no-tmux installs no-op every
// tick. Returns a stop function.
export function startTmuxStatusPoller(intervalMs = 1500): () => void {
  let running = false;
  const timer = setInterval(async () => {
    if (running) return;
    running = true;
    try {
      const bin = await tmuxBin();
      if (!bin) return;
      const proc = spawn(
        [bin, "-L", TMUX_SOCKET, "list-panes", "-a", "-F", "#{session_name} #{pane_current_command}"],
        { stdout: "pipe", stderr: "ignore" },
      );
      const out = await new Response(proc.stdout).text();
      await proc.exited;
      for (const line of out.split("\n")) {
        const sp = line.indexOf(" ");
        if (sp < 0) continue;
        const name = line.slice(0, sp);
        if (!name.startsWith("tt-")) continue;
        const id = name.slice(3);
        const meta = sessionMeta(id);
        if (!meta || meta.kind !== "shell") continue; // AI sessions are hook-driven
        const cmd = line.slice(sp + 1).trim();
        setStatus(id, IDLE_COMMANDS.has(cmd) ? "idle" : "running");
      }
    } catch {
      // tmux server not running / transient failure — skip this tick
    } finally {
      running = false;
    }
  }, intervalMs);
  return () => clearInterval(timer);
}
